name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name: 
        required: false
        description: The name of the deployable artifact files
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output information
        run: echo "Deploying & uploading..."